<?php
    include('home.php');
    // from previous page stored the Person's ID
    $keyword = $_SESSION['keyword'];

    // removing empty entry - dangerous things
    mysqli_query($db, "DELETE FROM People WHERE People_name = '';");

    $sql = "SELECT * FROM People WHERE CONCAT_WS('|', People_name, People_licence)
            LIKE '%$keyword%' ORDER BY People_name;";

    // reassign the query to $sql after looping back from a list of people generated
    //from the search (clicking on a link generated by <a href = '?ref=$id'>)
    if (isset($_GET['ref'])) {
        $sql = "SELECT People_ID FROM People WHERE People_ID = ".$_GET['ref'].";";
      }

    $result = mysqli_query($db, $sql);
    $row_count = mysqli_num_rows($result);

    if ($result != "") {
        if ($row_count == 0) {

            echo "Person not found";

        } else if ($row_count == 1) {
            // if the search come to one and exact one entry redirect to person_detail.php
            // setting session var for next page $_SESSION["People_ID"]
            $_SESSION["People_ID"] = mysqli_fetch_assoc($result)["People_ID"];
            header ("Location: person_detail.php");

        } else {
        // if there is more than one row return from query
        echo $row_count. " Person found:" ;
            echo "<ul>";  // start list
                // loop through each row of the result (each tuple will
                // be contained in the associative array $row)
                while($row = mysqli_fetch_assoc($result))
                    {
                    $p_id = $row["People_ID"];
                    echo "<li> <a href = '?ref=$p_id'>" . $row["People_name"]. "</a> " ;
                    if ($row["People_address"] != ""){
                        echo "(" . $row["People_address"]. ")"; }
                    }
                    echo "</ul>";

            }
        }

?>
<html>
<body>
    <form action="person_detail.php" method="post">
        <input type="submit" name="action" value="Add new person">
    </form><br>
</body>
</html>
